### ISSUE TITLE
Bug in \Concardis\Payengine\Lib\Internal\AbstractClass\AbstractResource::getOne()

### ISSUE THREAD

**Issue by ARoddis** [concardis/PHP_SDK#10]
There is a bug in the Line \Concardis\Payengine\Lib\Internal\AbstractClass\AbstractResource:140.

The Method is called with NULL, which replaces the DefaultValue of the second parameter (which is an empty array) and then explodes as "count" expects something countable, not NULL.

![grafik](https://user-images.githubusercontent.com/2421679/64425472-0b0f1180-d0ac-11e9-968f-51f37651040b.png)

And here:

![grafik](https://user-images.githubusercontent.com/2421679/64425498-195d2d80-d0ac-11e9-860e-9a34552956e5.png)

**Comment by kaihenkel** [comment]
This BUG is fixed with the PULL-Request https://github.com/concardis/PHP_SDK/pull/13

**Comment by kazemek** [comment]
Thanks guys, will close it.
