### ISSUE TITLE
Publish on https://packagist.org/

### ISSUE THREAD

**Issue by ocean90** [concardis/PHP_SDK#2]
Hi, I was wondering if there are any plans for publishing the SDK on packagist.org for easier use with composer?

**Comment by Sharenkamp** [comment]
Hi @ocean90,

yes we plan to publish the SDK on packagist.
We don't have a release date yet. 

best regards,
Stefan

**Comment by Sharenkamp** [comment]
Hi @ocean90,

we added the SDK to packagist.
https://packagist.org/packages/payengine/php_sdk
